---
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts


environments:
  dev:
  prod:

---
releases:
- name: kube-prometheus-stack
  namespace: monitoring
  chart: prometheus-community/kube-prometheus-stack
  version: 80.4.1
  installed: true
  createNamespace: true
  labels:
    app: kube-prometheus-stack
  values:
    - ./env/{{ .Environment.Name }}.yaml
