---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflow
  namespace: argo
spec:
  project: dev
  source:
    repoURL: https://github.com/ryoji1409/cluster-platform-manifests.git
    path: ./
    targetRevision: main
    plugin:
      name: helmfile
      parameters:
        - name: name
          string: argo-workflow
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo
spec:
  project: dev
  source:
    repoURL: https://github.com/ryoji1409/cluster-platform-manifests.git
    path: ./
    targetRevision: main
    plugin:
      name: helmfile
      parameters:
        - name: name
          string: argo-cd
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuberay-operator
  namespace: argo
spec:
  project: dev
  source:
    repoURL: https://github.com/ryoji1409/cluster-platform-manifests.git
    path: ./
    targetRevision: main
    plugin:
      name: helmfile
      parameters:
        - name: name
          string: kuberay-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: ray-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argo
spec:
  project: dev
  source:
    repoURL: https://github.com/ryoji1409/cluster-platform-manifests.git
    path: ./
    targetRevision: main
    plugin:
      name: helmfile
      parameters:
        - name: name
          string: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argo
spec:
  project: dev
  source:
    repoURL: https://github.com/ryoji1409/cluster-platform-manifests.git
    path: ./
    targetRevision: main
    plugin:
      name: helmfile
      parameters:
        - name: name
          string: metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argo
spec:
  project: dev
  source:
    repoURL: https://github.com/ryoji1409/cluster-platform-manifests.git
    path: ./
    targetRevision: main
    plugin:
      name: helmfile
      parameters:
        - name: name
          string: falco
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argo
spec:
  project: dev
  source:
    repoURL: https://github.com/ryoji1409/cluster-platform-manifests.git
    path: ./
    targetRevision: main
    plugin:
      name: helmfile
      parameters:
        - name: name
          string: jenkins
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whereabouts
  namespace: argo
spec:
  project: dev
  sources:
    - chart: whereabouts-chart
      repoURL: ghcr.io/k8snetworkplumbingwg
      targetRevision: 0.9.2
      helm:
        valueFiles:
        - $values/applications/whereabouts/env/dev.yaml
    - repoURL: https://github.com/ryoji1409/cluster-platform-manifests.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multus-nad
  namespace: argo
spec:
  project: dev
  source:
    repoURL: https://github.com/ryoji1409/cluster-platform-manifests.git
    path: applications/nad/environment/development
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: multus-nad
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argo
spec:
  project: dev
  source:
    repoURL: https://github.com/ryoji1409/cluster-platform-manifests.git
    path: ./
    targetRevision: main
    plugin:
      name: helmfile
      parameters:
        - name: name
          string: sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argo
spec:
  project: dev
  source:
    repoURL: https://github.com/ryoji1409/cluster-platform-manifests.git
    path: ./
    targetRevision: main
    plugin:
      name: helmfile
      parameters:
        - name: name
          string: vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
